### PR TITLE
ESP32S2 binary + PlatformIO library manager manifest

### PR DESCRIPTION
**Pull request by jesseklm**
- Added ESP32S2 binary from [community.bosch-sensortec.com](https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/BME-680-BSEC-for-ESP32-S2/m-p/60824/highlight/true#M12073)
- Added PlatformIO library manager manifest as in [BSEC-Arduino-library](https://github.com/BoschSensortec/BSEC-Arduino-library/pull/50)

### CODE REVIEW

**Comment by Blandi88** [comment]
This worked beautifully in 1.8.19 by the way.

**Comment by dcobbley** [comment]
Confirmed on ESP32S2 as well. Thanks for making this PR.

**Review by bilhelm96 — APPROVED** [review]
Works with PlatformIO on VS Code

**Comment by boschsensortec1** [comment]
Thank you @jesseklm

**Pull request merged**
